### ISSUE TITLE
Support "ref" as valid abbreviation in "react" package

### ISSUE THREAD

**Issue by thierry2015** [absolunet/eslint-config#1]
**Is your feature request related to a problem? Please describe.**
One frequent React variable name/suffix is `ref`, mostly through the `useRef()` hook. With the current configuration, `buttonRef` would be an error.

**Describe the solution you'd like**
As a developer, I would like to have `ref` excluded from the `unicorn/prevent-abbreviations` rule ([https://github.com/absolunet/eslint-config/blob/production/packages/react/shareable-config.yaml#L33](https://github.com/absolunet/eslint-config/blob/production/packages/react/shareable-config.yaml#L33)).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by meliacode** [comment]
Hi @thierry2015 

I just checked on a vanilla react project and have no problem with the `useRefs`. The `unicorn/prevent-abbreviations` rule only apply to the variable and not the react hook:

```
// contentRef is reported as an error but useRef is valid.
const contentRef = useRef();
```

I note the change you asked and adjust the rules on our next release.
Thank you

**Comment by thierry2015** [comment]
Yes @Essomia, the function itself causes no issue. But since the standard is to store its returned value in a `someRef` variable, I though it should get the same treatment as the `props` variable name.

**Comment by jblandry** [comment]
PR merged, will be in the next version
fefccedf3617a73a5aaa67ce377ca7fb0397c8c5
